config/routes.rb
Rails.application.routes.draw do

  # match 'services/all/edit' => 'services#edit_all', :as => :edit_all, :via => :get
  # get 'services/all/edit', to: 'services#edit_all', as: 'edit_all'
  # put 'services/all', to: 'services#update_all', as: 'update_all'
  # get 'services', to: 'services#index'

  resources :services

  get 'creatives/index'

  devise_for :admins, :controllers => {:registrations => "admins/registrations"}
  authenticated :admin do
    root 'services#index', as: :authenticated_root
  end


  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :micro_services, class_name: "Service", foreign_key: "macro_service_id"
  belongs_to :macro_service, class_name: "Service"

  accepts_nested_attributes_for :micro_services

  # orders micro_services by id (because heroku) and drops the first
  def normalize
    self.micro_services.sort_by{ |a| a[:id] }.drop(1)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  # GET /services
  # GET /services.json
  def index
    @services = Service.all.sort_by{ |a| a[:id]}[0..8]
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service.macro_service, notice: 'service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to services_url, notice: 'service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # def update_all
  #   params['price'].keys.each do |id|
  #     @price = Price.find(id.to_i)
  #     @price.update_attributes(params['price'][id].permit(:price))
  #   end
  #   redirect_to(prices_url)
  # end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:id, :price, :name, :macro_service_id, micro_services_attributes:[:id, :price, :name, :macro_service_id])
    end
end

app/views/services/edit.html.erb
<%= form_with(model: @service, local: true) do |form| %>

  <table class="table">
    <tr>
      <th> Nome </th>
      <th> Preço </th>
    </tr>

    <% @service.micro_services.sort_by{ |a| a[:id] }[1..-1].each do |service| %>
      <%= form.fields_for :micro_services, service do |f| %>
        <tr>
          <td>
            <%= f.text_field :name, class: "form-control" %>
          </td>
          <td>
            <%= f.text_field :price, class: "form-control" %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>

  <div class="actions">
    <%= submit_tag "Salvar", class: "btn btn-success"%>
  </div>

<% end %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Serviços</h1>

<table class="table">
  <% @services.each do |service| %>
    <tr>
      <td> <%= service.name %> </td>
      <td> <%= link_to 'Editar Preços', edit_service_path(service), class: "btn btn-success" %> </td>
      <td> <%= link_to 'Ver Serviços Atrelados', service_path(service), class: "btn btn-success" %> </td>
    </tr>
  <% end %>
</table>

app/views/services/new.html.erb
<%= form_with(model: @service, local: true) do |form| %>

  <table class="table">
    <tr>
      <th> Nome </th>
      <th> Preço </th>
    </tr>

    <tr>
      <td><%= form.text_field :name, class: "form-control" %></td>
      <td><%= form.text_field :price, class: "form-control" %></td>
    </tr>
  </table>


  <div class="actions">
    <%= form.hidden_field :macro_service_id, value: params[:format] %>
    <%= submit_tag "Salvar", class: "btn btn-success"%>
  </div>

<% end %>

app/views/services/show.html.erb
<h1><%= @service.name %></h1>

<table class="table">
  <% @service.micro_services.sort_by{ |a| a[:id] }[1..-1].each do |service| %>
    <tr>
      <td> <%= service.name %> </td>
      <td> <%= service.price %> </td>
      <!-- <td> <%= link_to 'Editar Preço', edit_service_path(service), class: "btn btn-success" %> </td> -->
      <td> <%= link_to 'Deletar Serviço', service_path(service), method: :delete, class: "btn btn-success" %> </td>
    </tr>
  <% end %>
</table>

<%= link_to 'Adicionar Serviço Atrelado', new_service_path(@service), class: "btn btn-success" %>