config/routes.rb
Rails.application.routes.draw do

  # match 'services/all/edit' => 'services#edit_all', :as => :edit_all, :via => :get
  # get 'services/all/edit', to: 'services#edit_all', as: 'edit_all'
  # put 'services/all', to: 'services#update_all', as: 'update_all'
  # get 'services', to: 'services#index'

  resources :services

  get 'creatives/index'

  devise_for :admins, :controllers => {:registrations => "admins/registrations"}
  authenticated :admin do
    root 'services#index', as: :authenticated_root
  end


  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>Clínica Aptidão</title>
    <%= stylesheet_link_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Clínica Aptidão</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/services">Serviços</a></li>
            <li><%= link_to 'Adicionar Admin', new_admin_registration_path %></</li>
          </ul>
          <ul class="nav navbar-nav navbar-right">

            <li><%= link_to 'Logout', destroy_admin_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="google-site-verification" content="wH_BWTfgzIPr6CEuxF-jwqa9xOI7bT3KJfesgHI2f7w" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-120720152-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-120720152-1');
    </script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clínica Aptidão</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Coustard" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/creative.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Start Bootstrap Creative</title>
  <%= stylesheet_link_tag 'creative/manifest.css', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'creative/manifest.js' %>
  <%= csrf_meta_tags %>
</head>

<body>
  

<%= yield %>

</body>
</html>